### ISSUE TITLE
UPDATE: FIXED: Chrome OS: Open JSTorrent first time, must download Web Server Chrome Library

### ISSUE THREAD

**Issue by brownielox45** [kzahel/jstorrent-legacy-app#141]
I downloaded JSTorrent on my Chromebook for the first on my Chromebook today. When I opened it up for the first time, I couldnt navigate JSTorrent and this message was on it:
![screenshot 2016-06-15 at 7 46 27 pm](https://cloud.githubusercontent.com/assets/19963131/16101272/3e198e7c-3332-11e6-9cc3-3177156ce689.png)

I downloaded Web Server Toolkit from the GitHub link first, that didnt work, than I downloaded it from the Chrome Web Store and selected the folder I was told to, but nothing changed.
![screenshot 2016-06-15 at 7 46 31 pm](https://cloud.githubusercontent.com/assets/19963131/16101306/7e400256-3332-11e6-8fef-fe0e29bacb1e.png)

Please help,

Jonathan

**Comment by brownielox45** [comment]
Ive fixed the issue by myself, so heres the soloution:

Instructions to download JSTorrent for Chrome OS:

1: Download JSTorrent ZIP off GitHub (Onto Chromebook NOT GOOGLE DRIVE)
2: Donwload Web Server Chrome ZIP (Onto Chromebook NOT GOOGLE DRIVE)
3: In Files app double-click: web-server-chrome-magic.ZIP
4: Copy Folder (web-server-chrome-magic)
5: Back in Files, Double Click: jstorrent-fresh.ZIP
6: Navigate to: jstorrent-fresh > js
7: Delete: jstorrent-fresh  > js > web-server-chrome
8: Paste previously copied folder (web-server-chrome-master)
9: Go back to jstorrent-fresh.ZIP, and copy all of the jstorrent-fresh folder (NOT .ZIP)
10: Open Files app, paste into Downloads

---

11: Open Chrome and go to: chrome://extensions/
12: Click the: Developer Mode checkbox
12: Click: Load Unpacked Extensions
13: In Files app opened, select the final: jstorrent-fresh file (NOT .ZIP)
14: Click: Open
15: Now that JSTorrent has appeared in your extension, click Launch and it should work fine!

NOTE: If it displays the same message as seen in my original Issue post above, you have done something wrong, please read instruction carefully, I have tried to make them as clear as possible.

-Jonathan

**Comment by ghost** [comment]
@brownielox45 What a fucking terrible instruction. It does nothing. What the fuck did you guys do to the extension?

**Comment by psonis** [comment]
@brownielox45 @ghost Steps 7 & 8 are wrong.
You don't need to delete folder jstorrent-fresh > js > web-server-chrome.
Its an empty folder. You just need to copy the contents of web-server-chrome-master folder into it.

**Comment by chetanDN** [comment]
I faced this problem. I followed these steps-
I assume that you have come up to above screenshot saying "Web Server Chrome Library Not Loaded and is now required. Get it"

Step1: Click Get it link there and download the zip from the github landing page (say zip2).
Step2: Unzip that "zip2" and copy the content from that extracted folder. (not the outer whole file but all the content inside that folder, Contents include like- Images folder, background.js buffer.js and other js files present).
Step3:Paste the content into your jstorrent extention folder( path: jstorrent-fresh>js>web-server-chrome folder(which would be empty before).

now from chrome://extensions click reload  and launch  jstorrent extention. It would work now.

**Comment by kawika54** [comment]
after reinstalling JSTorrent, and following the instructions, the app will launch, but then gets stuck on the "Settings" tab. I am unable to select a download place for the app to use.  please advise... thank you in advance.  also, there is no option to "reload and launch" the app in the chrome extentions.

**Comment by ajevans67** [comment]
I'm having the same issue. Followed instructions got it up without the error messages in the body, but the settings tab has a radiating red circle but will not respond when clicking on it. Has anyone found a solution to this???

**Comment by ajevans67** [comment]
Error in response to runtime.getBackgroundPage: TypeError: notification.updateTimestamp is not a function
    at AppForeground.createNotification (chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/gui/fgapp.js:592:26)
    at AppForeground.notifyNeedDownloadDirectory (chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/gui/fgapp.js:529:14)
    at clientready (chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/gui/ui.js:31:27)
    at ready (chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/gui/ui.js:36:17)
    at chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/gui/ui.js:46:13
    at HTMLDocument.onready (chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/gui/ui.js:11:20)

**Comment by ajevans67** [comment]
I went and bought the extension from Chrome and everything is working fine now

**Comment by protonpony** [comment]
Edit line 306 in session.js to say "this.analytics = null" ...or comment it out with "//". Bear in mind this version is still in development and full of unreleased code which may throw lots of other errors, some of them fatal, depending on your OS, browser, and settings.

**Comment by kzahel** [comment]
The legacy Chrome App is no longer maintained. I've rebuilt JSTorrent from scratch — the new version is ready at **[jstorrent.com](https://jstorrent.com)**

If you run into any issues, please leave feedback!
